### ISSUE TITLE
Upcoming code rejection

### ISSUE THREAD

**Issue by Silberling** [lukebitts/blend#4]
I have a conversion tool chat I updated today that started reporting

> warning: the following packages contain code that will be rejected by a future version of Rust: nom v5.1.2

using

`blend = "~0.6"`

On crates.io the recent version of nom is

`nom = "7.1.3"`

I haven't head the warning above any time using rust. I don't know how severe this is but at least it might sound urgent.

**Comment by lukebitts** [comment]
Thanks for the warning! I've published version 0.7 with a fix for this

**Comment by Silberling** [comment]
Perfect, thank you very much!
